parser: typescript
printWidth: 120
tabWidth: 2
singleQuote: true
trailingComma: "none"
useTabs: false
semi: true
arrowParens: avoid
ignorePath: .prettierignore
singleAttributePerLine: true
endOfLine: crlf
useEditorConfig: true

classSectionOrder: [properties, staticProperties, constructor, methods, staticMethods ]
classAccessibilityOrder: [private, protected, public]